name: proyecto_kinnin
description: "Kinnin – app de servicios médicos a domicilio"
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.8.1
  flutter: ">=3.35.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
